name: ARM64 Pull and Save Docker Image

on:
  workflow_dispatch:
    inputs:
      docker_images:
        description: '请填写docker镜像名称 多个用英文逗号分开'
        required: true
        default: 'alpine:latest,busybox:stable-glibc'  # 设置默认的 Docker 镜像列表
      docker_password:
        description: '请输入 aliyun docker 服务密码'
        required: true
        default: 'password' 

jobs:
  pull_and_package:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Pull Docker Images and Package
      run: |
        images="${{ github.event.inputs.docker_images }}"
        password="${{ github.event.inputs.docker_password }}"
          IFS=',' read -r -a image_array <<< "$images"
          for image in "${image_array[@]}"; do
            docker pull "${image}" --platform "linux/arm64"
            image_tag=${image/":"/"-"}
            image_tag=${image_tag//\//_}
            docker tag "${image}" crpi-w74i707dscu3e5f6.cn-shanghai.personal.cr.aliyuncs.com/jiangzhonghui/nvidia:${image_tag}
            echo "${password}" | docker login --username=kkry2333 --password-stdin crpi-w74i707dscu3e5f6.cn-shanghai.personal.cr.aliyuncs.com
            docker push crpi-w74i707dscu3e5f6.cn-shanghai.personal.cr.aliyuncs.com/jiangzhonghui/nvidia:${image_tag}
          done
          echo "Succeed to push to aliyuncs!"
          for image in "${image_array[@]}"; do
            docker save "${image}" -o "${image//\//_}-arm64.tar"
          done

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: ${{ github.workspace }}/*.tar.gz
        retention-days: 1  # 将保留天数设置为 1 天 最多可设置90天

